### GET FRIENDs
GET http://localhost:8383/friends

### GET FRIEND
GET http://localhost:8383/friends/james


### ADD A FRIEND
POST http://localhost:8383/addfriend
Content-Type: application/json

{
    "name": "banana",
    "status": "frieind"
}

### UPDATE STATUS OF A FRIEND
PATCH http://localhost:8383/changestatus
Content-Type: application/json

{
    "name": "tomato",
    "newStatus": "friend"
}


###DELETE A FRIEND
DELETE http://localhost:8383/friends
Content-Type: application/json

{
    "name": "banana"
}


